---
- name: Launch EC2
  local_action: ec2 key_name={{ key_name }} group={{ group }} instance_type={{ instance_type }} region={{ region }} image={{ image }} instance_tags={{ instance_tags }}
  register: ec2

- name: Add instance groupname 
  add_host: hostname={{ item.private_ip }} groups={{ group }}
  with_items: ec2.instances

- name: Wait for SSH to come up
  local_action: wait_for host={{ item.private_ip }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances

